### ISSUE TITLE
Navbar has rounded edges

### ISSUE THREAD

**Issue by GreenTurtwig** [GreenTurtwig/osu-info-Web#2]
![http://puu.sh/pALB5.png](http://puu.sh/pALB5.png)
:cat:

**Comment by dintendocoltd** [comment]
Tried to fix it by using <code>&lt;nav class="navbar navbar-default navbar-static-top" role="navigation"&gt;</code> and <code>&lt;nav class="navbar navbar-default navbar-fixed-top" role="navigation"&gt;</code> from the Bootstrap documentation.

It works, but it leaves some nasty unintended side effects (such as navbar tearing and page expansion). It would be far better to keep it the current way it is.

**Comment by GreenTurtwig** [comment]
Actually...
I found out that
```
.navbar {
  border-radius: 0;
}
```
works. 😺
